---
- name: "Copy netdata.conf template to /etc/netdata/netdata.conf"
  ansible.builtin.template:
    src: "{{ netdata_conf_template }}"
    dest: "/etc/netdata/netdata.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Restart netdata
