---
- name: "Ensure netdata-repo is removed (Debian Family)"
  become: true
  ansible.builtin.apt:
    name:
      - netdata-repo
      - netdata-repo-edge
    state: absent
    purge: true
  notify: "Update apt cache (Debian Family)"

- name: "Ensure gnupg is installed (Debian Family)"
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: "Add netdata repository"
  when: netdata_agent_state == "present"
  notify: "Update apt cache (Debian Family)"
  block:
    - name: "Ensure netdata repo key is present (Debian Family)"
      ansible.builtin.apt_key:
        url: https://repo.netdata.cloud/netdatabot.gpg.key
        state: present

    - name: "Ensure netdata repository is configured (Debian Family) [{{ netdata_agent_channel }}]"
      ansible.builtin.apt_repository:
        repo: "deb http://repo.netdata.cloud/repos/{{ netdata_agent_channel }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
        state: present
        filename: netdata-{{ netdata_agent_channel }}

    - name: "Set fact netdata_agent_channel_remove to edge"
      ansible.builtin.set_fact:
        netdata_agent_channel_remove: edge
      when: netdata_agent_channel == "stable"

    - name: "Set fact netdata_agent_channel_remove to stable"
      ansible.builtin.set_fact:
        netdata_agent_channel_remove: stable
      when: netdata_agent_channel == "edge"

    - name: "Ensure netdata repository is removed (Debian Family) [{{ netdata_agent_channel_remove }}]"
      ansible.builtin.apt_repository:
        repo: "deb http://repo.netdata.cloud/repos/{{ netdata_agent_channel_remove }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
        state: absent
        filename: netdata-{{ netdata_agent_channel_remove }}
      notify: "Remove netdata"

- name: "Remove netdata repository"
  when: netdata_agent_state == "absent"
  notify: "Update apt cache (Debian Family)"
  block:
    - name: "Ensure netdata repository is removed (Debian Family) [stable]"
      ansible.builtin.apt_repository:
        repo: "deb http://repo.netdata.cloud/repos/stable/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
        state: absent
        filename: netdata-stable

    - name: "Ensure netdata repository is removed (Debian Family) [edge]"
      ansible.builtin.apt_repository:
        repo: "deb http://repo.netdata.cloud/repos/edge}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
        state: absent
        filename: netdata-edge

    - name: "Ensure netdata repo key is removed (Debian Family)"
      ansible.builtin.apt_key:
        state: absent
        url: https://repo.netdata.cloud/netdatabot.gpg.key

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
