---
- name: "Ensure python3-debian and gnupg are installed (Debian Family)"
  ansible.builtin.apt:
    name:
      - gnupg
      - python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure legacy netdata-repo packages are removed (Debian Family)"
  ansible.builtin.apt:
    name:
      - netdata-repo
      - netdata-repo-edge
    state: absent
    purge: true
  notify: "Update apt cache"

- name: "Ensure old netdata stable apt_repository definition is removed (Legacy)"
  ansible.builtin.apt_repository:
    repo: "deb http://repo.netdata.cloud/repos/stable/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
    state: absent
    filename: netdata-stable
  notify: "Update apt cache"

- name: "Ensure old netdata edge apt_repository definition is removed (Legacy)"
  ansible.builtin.apt_repository:
    repo: "deb http://repo.netdata.cloud/repos/edge/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
    state: absent
    filename: netdata-edge
  notify: "Update apt cache"

- name: "Remove legacy netdata repo key via apt_key when available (Debian <=12)"
  ansible.builtin.apt_key:
    state: absent
    id: 0x6588FDD7B14721FE7C3115E6F9177B5265F56346
  when: ansible_distribution == "Debian" and (ansible_distribution_major_version | int) < 13
  notify: "Update apt cache"

- name: "Ensure legacy netdata-stable.list is removed"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/netdata-stable.list"
    state: absent
  notify: "Update apt cache"

- name: "Ensure legacy netdata-edge.list is removed"
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/netdata-edge.list"
    state: absent
  notify: "Update apt cache"

- name: "Determine repository channel to remove (opposite of selected)"
  ansible.builtin.set_fact:
    netdata_agent_channel_remove: "{{ 'edge' if netdata_agent_channel == 'stable' else 'stable' }}"



- name: "Add Netdata repository (deb822) for channel {{ netdata_agent_channel }}"
  ansible.builtin.deb822_repository:
    name: netdata-{{ netdata_agent_channel }}
    types: [deb]
    uris: "http://repo.netdata.cloud/repos/{{ netdata_agent_channel }}/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release | lower }}/"
    signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
    enabled: true
    state: "{{ 'present' if netdata_agent_state == 'present' else 'absent' }}"
  when: netdata_agent_state in ['present', 'absent']
  notify: "Update apt cache"

- name: "Ensure opposite channel repository is removed (deb822)"
  ansible.builtin.deb822_repository:
    name: netdata-{{ netdata_agent_channel_remove }}
    types: [deb]
    uris: "http://repo.netdata.cloud/repos/{{ netdata_agent_channel_remove }}/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release | lower }}/"
    signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
    enabled: true
    state: absent
  when: netdata_agent_state == "present"
  notify:
    - "Remove netdata"
    - "Update apt cache"

- name: "Remove Netdata repository when state=absent (ensure both channels gone)"
  when: netdata_agent_state == "absent"
  block:
    - name: "Remove stable repository (deb822)"
      ansible.builtin.deb822_repository:
        name: netdata-stable
        types: [deb]
        uris: "http://repo.netdata.cloud/repos/stable/{{ ansible_distribution | lower }}"
        suites: "{{ ansible_distribution_release | lower }}/"
        signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
        enabled: true
        state: absent
    - name: "Remove edge repository (deb822)"
      ansible.builtin.deb822_repository:
        name: netdata-edge
        types: [deb]
        uris: "http://repo.netdata.cloud/repos/edge/{{ ansible_distribution | lower }}"
        suites: "{{ ansible_distribution_release | lower }}/"
        signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
        enabled: true
        state: absent
  notify: "Update apt cache"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
