---
- name: "Ensure netdata-repo is removed (Debian Family) [Legacy]"
  become: true
  ansible.builtin.apt:
    name:
      - netdata-repo
      - netdata-repo-edge
    state: absent
    purge: true
  notify: "Update apt cache"

- name: "Ensure python3-debian and gnupg is installed (Debian Family)"
  ansible.builtin.apt:
    name:
      - gnupg
      - python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure netdata repository is removed (Debian Family) [Legacy]: stable"
  ansible.builtin.apt_repository:
    repo: "deb http://repo.netdata.cloud/repos/stable/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
    state: absent
    filename: netdata-stable

- name: "Ensure netdata repository is removed (Debian Family) [Legacy]: edge"
  ansible.builtin.apt_repository:
    repo: "deb http://repo.netdata.cloud/repos/edge}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }}/"
    state: absent
    filename: netdata-edge

- name: "Ensure netdata repo key is removed from legacy trusted.gpg keyring (Debian Family) [Legacy]"
  ansible.builtin.apt_key:
    state: absent
    id: 0x6588FDD7B14721FE7C3115E6F9177B5265F56346

- name: "Set fact netdata_agent_channel_remove to edge"
  ansible.builtin.set_fact:
    netdata_agent_channel_remove: edge
  when: netdata_agent_channel == "stable"

- name: "Set fact netdata_agent_channel_remove to stable"
  ansible.builtin.set_fact:
    netdata_agent_channel_remove: stable
  when: netdata_agent_channel == "edge"

- name: "Add netdata repository"
  when: netdata_agent_state == "present"
  notify: "Update apt cache"
  block:
    - name: "Ensure netdata repository is configured (Debian Family): {{ netdata_agent_channel }}"
      ansible.builtin.deb822_repository:
        name: netdata-{{ netdata_agent_channel }}
        uris: "http://repo.netdata.cloud/repos/{{ netdata_agent_channel }}/{{ ansible_distribution | lower }}"
        signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
        suites: "{{ ansible_distribution_release | lower }}/"
        state: present
        enabled: true

    - name: "Ensure netdata repository is removed (Debian Family): {{ netdata_agent_channel_remove }}"
      ansible.builtin.deb822_repository:
        name: netdata-{{ netdata_agent_channel_remove }}
        uris: "http://repo.netdata.cloud/repos/{{ netdata_agent_channel_remove }}/{{ ansible_distribution | lower }}"
        signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
        suites: "{{ ansible_distribution_release | lower }}/"
        state: absent
        enabled: true
      notify: "Remove netdata"

- name: "Remove netdata repository"
  when: netdata_agent_state == "absent"
  notify: "Update apt cache"
  block:
    - name: "Ensure netdata repository is removed (Debian Family): {{ netdata_agent_channel }}"
      ansible.builtin.deb822_repository:
        name: netdata-{{ netdata_agent_channel }}
        uris: "http://repo.netdata.cloud/repos/{{ netdata_agent_channel }}/{{ ansible_distribution | lower }}"
        signed_by: "https://repo.netdata.cloud/netdatabot.gpg.key"
        suites: "{{ ansible_distribution_release | lower }}/"
        state: absent
        enabled: true

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
