---
- name: "Verify"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Get service facts"
      ansible.builtin.service_facts:

    - name: "Check netdata service is started"
      ansible.builtin.fail:
        msg: "netdata service is not started"
      when: "'netdata' in services and services['netdata']['state'] != 'running'"

    - name: "Check netdata service is enabled"
      ansible.builtin.fail:
        msg: "netdata service is not enabled"
      when: "'netdata' in services and services['netdata.service']['status'] != 'enabled'"

    - name: "Check netdata dashboard port to open"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "19999"
        state: started
        delay: 5
        timeout: 10
