---
- name: "Verify"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check if /tmp/unsupported_distro file exists"
      ansible.builtin.stat:
        path: "/tmp/unsupported_distro"
      register: unsupported_distro_file

    - name: "Verify"
      when: not unsupported_distro_file.stat.exists
      block:
        - name: "Get service facts"
          ansible.builtin.service_facts:

        - name: "Check netdata service is stopped"
          ansible.builtin.fail:
            msg: "Netdata service is started"
          when: "'netdata' in services and services['netdata']['state'] == 'started'"

        - name: "Check netdata dashboard port to closed"
          ansible.builtin.wait_for:
            host: "{{ inventory_hostname }}"
            port: "19999"
            state: stopped
            delay: 5
            timeout: 10
