---
# handlers file for netdata

- name: "Restart netdata"
  become: true
  ansible.builtin.service:
    name: netdata
    state: restarted

- name: "Remove netdata"
  become: true
  ansible.builtin.package:
    name: netdata
    state: absent

- name: "Remove netdata zypper"
  become: true
  community.general.zypper:
    name: netdata
    state: absent

- name: "Update apt cache"
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_pkg_mgr == "apt"

- name: "Update dnf cache"
  become: true
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_pkg_mgr == "dnf"

- name: "Update yum cache"
  become: true
  ansible.builtin.yum:
    update_cache: true
  when: ansible_pkg_mgr == "yum"
