---
- name: "Converge"
  hosts: all
  gather_facts: false
  vars:
    netdata_cloud_enable: true
    netdata_cloud_claim_token: this-is-a-test-token
    netdata_cloud_claim_room_id: this-is-a-test-token
    netdata_agent_web_enabled: false
  roles:
    - role: "dgibbs64.netdata"
