---
- name: "Verify"
  hosts: all
  gather_facts: false
  tasks:
    - name: "Get service facts"
      ansible.builtin.service_facts:

    - name: "Check netdata service is started"
      ansible.builtin.fail:
        msg: "Netdata service is stopped"
      when: "'netdata' in services and services['netdata']['state'] == 'stopped'"

    - name: "Wait for netdata dashboard port to open"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "19999"
        state: stopped
        delay: 1
        timeout: 10
      register: result

    - name: "Print port status"
      ansible.builtin.debug:
        msg: "Port 19999 is open: {{ result.elapsed }}"
